repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        name: check for added large files
        description: prevents giant files from being committed.
        entry: check-added-large-files
        language: python
        stages: [commit, push, manual]
        exclude: ^tx

  - repo: local
    hooks:
      - id: actionlint
        name: actionlint
        entry: actionlint
        language: golang
        additional_dependencies:
          [github.com/rhysd/actionlint/cmd/actionlint@v1.6.23]
        types: [yaml]
        files: '^.github/workflows/'

##########
# pre-commit-ci config

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
