version: '2'

services:
  assertionservice-app:
    restart: unless-stopped
    image: ${DOCKER_REG}/assertionservice:${TAG}
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
      - 'SPRING_DATA_MONGODB_URI=${MONGO_DB}'
      - SPRING_DATA_MONGODB_DATABASE=assertionservice
      - JHIPSTER_SLEEP=30
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - 'APPLICATION_ORCIDAPIENDPOINT=${ORCID_API_ENDPOINT}'
      - 'APPLICATION_JWT_SIGNATURE_URL=${JWT_SIGNATURE_URL}'
      - 'APPLICATION_LANDING_PAGE_URL=${LANDING_PAGE_URL}'
      - 'APPLICATION_TOKEN_EXCHANGE_ENDPOINT=${TOKEN_EXCHANGE_ENDPOINT}'
      - 'APPLICATION_TOKEN_EXCHANGE_GRANT_TYPE=${TOKEN_EXCHANGE_GRANT_TYPE}'
      - 'APPLICATION_TOKEN_EXCHANGE_SUBJECT_TOKEN_TYPE=${TOKEN_EXCHANGE_SUBJECT_TOKEN_TYPE}'
      - 'APPLICATION_TOKEN_EXCHANGE_REQUESTED_TOKEN_TYPE=${TOKEN_EXCHANGE_REQUESTED_TOKEN_TYPE}'
      - 'APPLICATION_TOKEN_EXCHANGE_CLIENT_ID=${TOKEN_EXCHANGE_CLIENT_ID}'
      - 'APPLICATION_TOKEN_EXCHANGE_CLIENT_SECRET=${TOKEN_EXCHANGE_CLIENT_SECRET}'
      - APPLICATION_SYNC_AFFILIATIONS_DELAY=${CRON_SYNC_AFFILIATIONS}
      - JHIPSTER_MAIL_BASE_URL=${BASE_URL}
      - OAUTH2_WEB_CLIENT_CONFIGURATION_SECRET=${WEB_CLIENT_CONFIGURATION_SECRET}
      - MEMBER_ASSERTION_STATS_CRON=${CRON_GENERATE_MEMBER_ASSERTION_STATS}
      - APPLICATION_MAIL_DOMAIN=${MAIL_DOMAIN}
      - APPLICATION_MAIL_API_KEY=${MAIL_API_KEY}
      - APPLICATION_MAIL_API_URL=${MAIL_API_URL}
      - APPLICATION_MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - APPLICATION_MAIL_FROM_NAME=${MAIL_FROM_NAME}
      - MEMBER_ASSERTION_STATS_RECIPIENT=${MEMBER_ASSERTION_STATS_RECIPIENT}
      - STORED_FILE_LIFESPAN=${STORED_FILE_LIFESPAN}
    volumes:
      - ${LOG_VOLUME:-/var/tmp/}:/logs
      - ${MEMBER_ASSERTION_STATS_VOLUME}:/files
    depends_on:
      - "jhipster-registry"

  gateway-app:
    restart: unless-stopped
    image: ${DOCKER_REG}/gateway:${TAG}-${ENV}
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
      - 'SPRING_DATA_MONGODB_URI=${MONGO_DB}'
      - SPRING_DATA_MONGODB_DATABASE=gateway
      - JHIPSTER_SLEEP=30
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - BASE_URL=${BASE_URL}
      - OAUTH2_WEB_CLIENT_CONFIGURATION_SECRET=${WEB_CLIENT_CONFIGURATION_SECRET}
      - GATEWAY_COOKIE_DOMAIN=${COOKIE_DOMAIN}
    volumes:
      - ${LOG_VOLUME:-/var/tmp/}:/logs
    ports:
      - '8080:8080'
    depends_on:
      - "jhipster-registry"

  userservice-app:
    restart: unless-stopped
    image: ${DOCKER_REG}/userservice:${TAG}
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
      - 'SPRING_DATA_MONGODB_URI=${MONGO_DB}'
      - SPRING_DATA_MONGODB_DATABASE=userservice
      - JHIPSTER_SLEEP=30
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - APPLICATION_MAIL_DOMAIN=${MAIL_DOMAIN}
      - APPLICATION_MAIL_API_KEY=${MAIL_API_KEY}
      - APPLICATION_MAIL_API_URL=${MAIL_API_URL}
      - APPLICATION_MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - APPLICATION_BASE_URL=${BASE_URL}
      - APPLICATION_MAIL_FROM_NAME=${MAIL_FROM_NAME}
      - UAA_WEB_CLIENT_CONFIGURATION_SECRET=${WEB_CLIENT_CONFIGURATION_SECRET}
      - UAA_KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
      - UAA_KEYSTORE_NAME=${KEYSTORE_LOCATION}
      - APPLICATION_ENCRYPT_SALT=${ENCRYPT_SALT}
      - APPLICATION_ENCRYPT_KEY=${ENCRYPT_KEY}
    volumes:
      - ${LOG_VOLUME:-/var/tmp/}:/logs
      - ${HOST_KEYSTORE_DIR}:/keystores
    depends_on:
      - "jhipster-registry"

  memberservice-app:
    restart: unless-stopped
    image: ${DOCKER_REG}/memberservice:${TAG}
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
      - 'SPRING_DATA_MONGODB_URI=${MONGO_DB}'
      - SPRING_DATA_MONGODB_DATABASE=memberservice
      - JHIPSTER_SLEEP=30
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - OAUTH2_WEB_CLIENT_CONFIGURATION_SECRET=${WEB_CLIENT_CONFIGURATION_SECRET}
      - 'APPLICATION_ORCIDORGCLIENTID=${ORCID_ORG_CLIENTID}'
      - 'APPLICATION_ORCIDORGSALESFORCEID=${ORCID_ORG_SALESFORCEID}'
      - HOLISTICS_MEMBER_DASHBOARD_URL=${HOLISTICS_MEMBER_DASHBOARD_URL}
      - HOLISTICS_MEMBER_DASHBOARD_SECRET=${HOLISTICS_MEMBER_DASHBOARD_SECRET}
      - HOLISTICS_INTEGRATION_DASHBOARD_URL=${HOLISTICS_INTEGRATION_DASHBOARD_URL}
      - HOLISTICS_INTEGRATION_DASHBOARD_SECRET=${HOLISTICS_INTEGRATION_DASHBOARD_SECRET}
      - HOLISTICS_CONSORTIA_DASHBOARD_URL=${HOLISTICS_CONSORTIA_DASHBOARD_URL}
      - HOLISTICS_CONSORTIA_DASHBOARD_SECRET=${HOLISTICS_CONSORTIA_DASHBOARD_SECRET}
    volumes:
      - ${LOG_VOLUME:-/var/tmp/}:/logs
    depends_on:
      - "jhipster-registry"

  jhipster-registry:
    restart: unless-stopped
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry

  r7insight_docker:
    restart: unless-stopped
    image: rapid7/r7insight_docker:4.0.0
    security_opt:
      - no-new-privileges
    environment:
      - INSIGHT_TOKEN=${INSIGHT_TOKEN}
    command: -r us -j --no-stats --no-docker-events --skipByName '.*jhipster-registry.*'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


