#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZTIzYjk2ZTg5MTA5MDQxMjZlNjk2M2I3MzFjMmQ0ZGNlODU2ZGViMDcxMzE5ZmQxMjlkYTVjZDZiZmIyNDFlYzYyYzE0YTE4ODU5YjUyYjczZWIzNWFiZDg3N2Q1NTFhZWIwNA==
  logging:
    logstash:
      enabled: true
      host: localhost # If using a Virtual Machine on Mac OS X or Windows with docker-machine, use the Docker's host IP here
      port: 5000
      queueSize: 512
  metrics:
    logs:
      enabled: true
      reportFrequency: 60 # seconds

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
