name: Angular CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies and run tests
        working-directory: ui
        run: |
          npm i
          npm test