name: Old UI Cypress end to end tests

on:
  workflow_dispatch:

jobs:
  csv-add-affiliations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Create creds json"
        id: create-creds-json
        uses: jsdaniell/create-json@1.2.3
        with:
          name: "credentials.json"
          json: '{"adminEmail": "${{secrets.CY_ADMIN_EMAIL}}", "adminPassword": "${{secrets.CY_ADMIN_PASSWORD}}", "password": "${{secrets.CY_PASSWORD}}", "shortPassword": "${{secrets.CY_SHORT_PASSWORD}}", "shortConfirmationPassword": "${{secrets.CY_SHORT_CONFIRMATION_PASSWORD}}", "wrongConfirmationPasssword": "${{secrets.CY_WRONG_CONFIRMATION_PASSWORD}}"}'
          dir: "gateway/cypress/fixtures"
      - name: "Create Gmail creds json"
        id: create-gmail-creds-file
        uses: jsdaniell/create-json@1.2.3
        with:
          name: "credentials_qa.json"
          json: '{"installed":{"client_id":"${{secrets.CY_CREDS_CLIENT_ID}}","project_id":"${{secrets.CY_CREDS_PROJECT_ID}}","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"${{secrets.CY_CREDS_CLIENT_SECRET}}","redirect_uris":["urn:ietf:wg:oauth:2.0:oob","http://localhost"]}}'
          dir: "gateway/cypress/plugins"
      - name: "Create Gmail token json"
        id: create-gmail-token-file
        uses: jsdaniell/create-json@1.2.3
        with:
          name: "token_qa.json"
          json: '{"access_token":"${{secrets.CY_TOKEN_ACCESS}}","refresh_token":"${{secrets.CY_TOKEN_REFRESH}}","scope":"https://www.googleapis.com/auth/gmail.readonly https://www.googleapis.com/auth/gmail.send","token_type":"Bearer","expiry_date":${{secrets.CY_TOKEN_EXPIRY_DATE}}}'
          dir: "gateway/cypress/plugins"
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install-command: npm install cypress --legacy-peer-deps
          working-directory: gateway
          spec: cypress/integration/retention/csv-add-affiliations.js
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: gateway/cypress/screenshots
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos
          path: gateway/cypress/videos
  csv-edit-affiliations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Create creds json"
        id: create-creds-json
        uses: jsdaniell/create-json@1.2.3
        with:
          name: "credentials.json"
          json: '{"adminEmail": "${{secrets.CY_ADMIN_EMAIL}}", "adminPassword": "${{secrets.CY_ADMIN_PASSWORD}}", "password": "${{secrets.CY_PASSWORD}}", "shortPassword": "${{secrets.CY_SHORT_PASSWORD}}", "shortConfirmationPassword": "${{secrets.CY_SHORT_CONFIRMATION_PASSWORD}}", "wrongConfirmationPasssword": "${{secrets.CY_WRONG_CONFIRMATION_PASSWORD}}"}'
          dir: "gateway/cypress/fixtures"
      - name: "Create Gmail creds json"
        id: create-gmail-creds-file
        uses: jsdaniell/create-json@1.2.3
        with:
          name: "credentials_qa.json"
          json: '{"installed":{"client_id":"${{secrets.CY_CREDS_CLIENT_ID}}","project_id":"${{secrets.CY_CREDS_PROJECT_ID}}","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"${{secrets.CY_CREDS_CLIENT_SECRET}}","redirect_uris":["urn:ietf:wg:oauth:2.0:oob","http://localhost"]}}'
          dir: "gateway/cypress/plugins"
      - name: "Create Gmail token json"
        id: create-gmail-token-file
        uses: jsdaniell/create-json@1.2.3
        with:
          name: "token_qa.json"
          json: '{"access_token":"${{secrets.CY_TOKEN_ACCESS}}","refresh_token":"${{secrets.CY_TOKEN_REFRESH}}","scope":"https://www.googleapis.com/auth/gmail.readonly https://www.googleapis.com/auth/gmail.send","token_type":"Bearer","expiry_date":${{secrets.CY_TOKEN_EXPIRY_DATE}}}'
          dir: "gateway/cypress/plugins"
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install-command: npm install cypress --legacy-peer-deps
          working-directory: gateway
          spec: |
            cypress/integration/retention/csv-edit-affiliations.js
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: gateway/cypress/screenshots
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos
          path: gateway/cypress/videos
  add-affiliation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Create creds json"
        id: create-creds-json
        uses: jsdaniell/create-json@1.2.3
        with:
          name: "credentials.json"
          json: '{"adminEmail": "${{secrets.CY_ADMIN_EMAIL}}", "adminPassword": "${{secrets.CY_ADMIN_PASSWORD}}", "password": "${{secrets.CY_PASSWORD}}", "shortPassword": "${{secrets.CY_SHORT_PASSWORD}}", "shortConfirmationPassword": "${{secrets.CY_SHORT_CONFIRMATION_PASSWORD}}", "wrongConfirmationPasssword": "${{secrets.CY_WRONG_CONFIRMATION_PASSWORD}}"}'
          dir: "gateway/cypress/fixtures"
      - name: "Create Gmail creds json"
        id: create-gmail-creds-file
        uses: jsdaniell/create-json@1.2.3
        with:
          name: "credentials_qa.json"
          json: '{"installed":{"client_id":"${{secrets.CY_CREDS_CLIENT_ID}}","project_id":"${{secrets.CY_CREDS_PROJECT_ID}}","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"${{secrets.CY_CREDS_CLIENT_SECRET}}","redirect_uris":["urn:ietf:wg:oauth:2.0:oob","http://localhost"]}}'
          dir: "gateway/cypress/plugins"
      - name: "Create Gmail token json"
        id: create-gmail-token-file
        uses: jsdaniell/create-json@1.2.3
        with:
          name: "token_qa.json"
          json: '{"access_token":"${{secrets.CY_TOKEN_ACCESS}}","refresh_token":"${{secrets.CY_TOKEN_REFRESH}}","scope":"https://www.googleapis.com/auth/gmail.readonly https://www.googleapis.com/auth/gmail.send","token_type":"Bearer","expiry_date":${{secrets.CY_TOKEN_EXPIRY_DATE}}}'
          dir: "gateway/cypress/plugins"
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install-command: npm install cypress --legacy-peer-deps
          working-directory: gateway
          spec: |
            cypress/integration/retention/add-affiliation.js
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: gateway/cypress/screenshots
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos
          path: gateway/cypress/videos
  notifications:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Create creds json"
        id: create-creds-json
        uses: jsdaniell/create-json@1.2.3
        with:
          name: "credentials.json"
          json: '{"adminEmail": "${{secrets.CY_ADMIN_EMAIL}}", "adminPassword": "${{secrets.CY_ADMIN_PASSWORD}}", "password": "${{secrets.CY_PASSWORD}}", "shortPassword": "${{secrets.CY_SHORT_PASSWORD}}", "shortConfirmationPassword": "${{secrets.CY_SHORT_CONFIRMATION_PASSWORD}}", "wrongConfirmationPasssword": "${{secrets.CY_WRONG_CONFIRMATION_PASSWORD}}"}'
          dir: "gateway/cypress/fixtures"
      - name: "Create Gmail creds json"
        id: create-gmail-creds-file
        uses: jsdaniell/create-json@1.2.3
        with:
          name: "credentials_qa.json"
          json: '{"installed":{"client_id":"${{secrets.CY_CREDS_CLIENT_ID}}","project_id":"${{secrets.CY_CREDS_PROJECT_ID}}","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"${{secrets.CY_CREDS_CLIENT_SECRET}}","redirect_uris":["urn:ietf:wg:oauth:2.0:oob","http://localhost"]}}'
          dir: "gateway/cypress/plugins"
      - name: "Create Gmail token json"
        id: create-gmail-token-file
        uses: jsdaniell/create-json@1.2.3
        with:
          name: "token_qa.json"
          json: '{"access_token":"${{secrets.CY_TOKEN_ACCESS}}","refresh_token":"${{secrets.CY_TOKEN_REFRESH}}","scope":"https://www.googleapis.com/auth/gmail.readonly https://www.googleapis.com/auth/gmail.send","token_type":"Bearer","expiry_date":${{secrets.CY_TOKEN_EXPIRY_DATE}}}'
          dir: "gateway/cypress/plugins"
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install-command: npm install cypress --legacy-peer-deps
          working-directory: gateway
          spec: |
            cypress/integration/retention/notifications.js
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: gateway/cypress/screenshots
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos
          path: gateway/cypress/videos
  other-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Create creds json"
        id: create-creds-json
        uses: jsdaniell/create-json@1.2.3
        with:
          name: "credentials.json"
          json: '{"adminEmail": "${{secrets.CY_ADMIN_EMAIL}}", "adminPassword": "${{secrets.CY_ADMIN_PASSWORD}}", "password": "${{secrets.CY_PASSWORD}}", "shortPassword": "${{secrets.CY_SHORT_PASSWORD}}", "shortConfirmationPassword": "${{secrets.CY_SHORT_CONFIRMATION_PASSWORD}}", "wrongConfirmationPasssword": "${{secrets.CY_WRONG_CONFIRMATION_PASSWORD}}"}'
          dir: "gateway/cypress/fixtures"
      - name: "Create Gmail creds json"
        id: create-gmail-creds-file
        uses: jsdaniell/create-json@1.2.3
        with:
          name: "credentials_qa.json"
          json: '{"installed":{"client_id":"${{secrets.CY_CREDS_CLIENT_ID}}","project_id":"${{secrets.CY_CREDS_PROJECT_ID}}","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"${{secrets.CY_CREDS_CLIENT_SECRET}}","redirect_uris":["urn:ietf:wg:oauth:2.0:oob","http://localhost"]}}'
          dir: "gateway/cypress/plugins"
      - name: "Create Gmail token json"
        id: create-gmail-token-file
        uses: jsdaniell/create-json@1.2.3
        with:
          name: "token_qa.json"
          json: '{"access_token":"${{secrets.CY_TOKEN_ACCESS}}","refresh_token":"${{secrets.CY_TOKEN_REFRESH}}","scope":"https://www.googleapis.com/auth/gmail.readonly https://www.googleapis.com/auth/gmail.send","token_type":"Bearer","expiry_date":${{secrets.CY_TOKEN_EXPIRY_DATE}}}'
          dir: "gateway/cypress/plugins"
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install-command: npm install cypress --legacy-peer-deps
          working-directory: gateway
          spec: |
            cypress/integration/retention/add-member.js
            cypress/integration/retention/add-user.js
            cypress/integration/retention/csv-invalid-affiliation.js
            cypress/integration/retention/edit-affiliation.js
            cypress/integration/retention/edit-member.js
            cypress/integration/retention/edit-user.js
            cypress/integration/retention/reset-password.js
            cypress/integration/retention/restricted-access.js
            cypress/integration/retention/ui-authorities.js
            cypress/integration/retention/ui-login.js
            cypress/integration/retention/ui-pagination.js
            cypress/integration/retention/ui-homepage.js
            cypress/integration/retention/ui-homepage-edit.js
            cypress/integration/retention/ui-reports.js
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: gateway/cypress/screenshots
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos
          path: gateway/cypress/videos
