# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build Gateway service
      run: mvn -B verify --file gateway/pom.xml -Dangular.env=qa -Pprod
    - name: Build User service
      run: mvn -B verify --file user-service/pom.xml -Pprod
    - name: Build Assertion service
      run: mvn -B verify --file assertion-service/pom.xml -Pprod
    - name: Build Member service
      run: mvn -B verify --file member-service/pom.xml -Pprod
