# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
    - name: Build Gateway service
      run: mvn -B verify -Dangular.env=qa -Pprod --file gateway/pom.xml 
    - name: Build User service
      run: mvn -B verify  -Pprod --file user-service/pom.xml
    - name: Build Assertion service
      run: mvn -B verify -Pprod --file assertion-service/pom.xml
    - name: Build Member service
      run: mvn -B verify -Pprod --file member-service/pom.xml
    - name: Build Discovery service
      run: mvn -B verify -Pprod --file discovery-service/pom.xml
    - uses: actions/checkout@v3
    - name: Use Node.js v16.13.2
      uses: actions/setup-node@v3
      with:
        node-version: v16.13.2
    - name: Install dependencies
      run: npm ci
      working-directory: ./gateway
    - name: Build
      run: npm run webpack:qa:main
      working-directory: ./gateway
